backend:
  name: git-gateway
  branch: main  # Hoặc master nếu repo của bạn dùng master

media_folder: "assets/uploads"      # Thư mục chứa ảnh upload (trong repo)
public_folder: "/assets/uploads"    # Đường dẫn public

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
